### PR TITLE
Blender 2.80

### PR DESCRIPTION
**Pull request by MarioCMFlys**
#9 Implements changes necessary for Blender 2.80 support

### CODE REVIEW

**Review by IIK3D — COMMENTED** [review]
Hello, we got the same idea !
was you able to fix dependency cyclic?

**Comment by JacquesLucke** [comment]
I haven't tested the changes, but they look all good.

If you plan to do more changes to this addon, I can add you as a collaborator to the project. This way you could commit fixes like this one to master directly.

**Comment by MarioCMFlys** [comment]
I wanted to try this addon after moving to Blender 2.8, and I plan to use it, so I may continue updating it to update for future versions.
When testing my changes I did not notice any functional differences, so if you find one, let me know and I'll try to fix them!

**Comment by JacquesLucke** [comment]
I gave you access to the repo. You can commit this patch to master yourself.

**Review by JacquesLucke — APPROVED** [review]

**Pull request merged**
